/* Generated by Yosys 0.41+108 (git sha1 557968567, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* hdlname = "sram" *)
(* top =  1  *)
(* src = "sram.v:1.1-20.10" *)
module sram(en, ysw, ysr, add, din, dout);
  (* src = "sram.v:11.5-18.8" *)
  wire [2:0] _00_;
  (* src = "sram.v:11.5-18.8" *)
  wire [7:0] _01_;
  (* src = "sram.v:15.17-15.20" *)
  wire [7:0] _02_;
  wire [7:0] _03_;
  (* src = "sram.v:4.17-4.20" *)
  input [2:0] add;
  wire [2:0] add;
  (* src = "sram.v:5.17-5.20" *)
  input [7:0] din;
  wire [7:0] din;
  (* src = "sram.v:6.22-6.26" *)
  output [7:0] dout;
  reg [7:0] dout;
  (* src = "sram.v:2.11-2.13" *)
  input en;
  wire en;
  (* src = "sram.v:3.15-3.18" *)
  input ysr;
  wire ysr;
  (* src = "sram.v:3.11-3.14" *)
  input ysw;
  wire ysw;
  (* src = "sram.v:9.15-9.18" *)
  reg [7:0] ram [7:0];
  always @(posedge en) begin
    if (ysw)
      ram[_00_] <= _01_;
  end
  assign _02_ = ram[add];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[0] <= _03_[0];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[1] <= _03_[1];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[2] <= _03_[2];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[3] <= _03_[3];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[4] <= _03_[4];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[5] <= _03_[5];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[6] <= _03_[6];
  (* src = "sram.v:11.5-18.8" *)
  always @(posedge en)
    if (!ysw) dout[7] <= _03_[7];
  assign _01_[0] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[0] : 1'hx;
  assign _01_[1] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[1] : 1'hx;
  assign _01_[2] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[2] : 1'hx;
  assign _01_[3] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[3] : 1'hx;
  assign _01_[4] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[4] : 1'hx;
  assign _01_[5] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[5] : 1'hx;
  assign _01_[6] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[6] : 1'hx;
  assign _01_[7] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) din[7] : 1'hx;
  assign _00_[0] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) add[0] : 1'hx;
  assign _00_[1] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) add[1] : 1'hx;
  assign _00_[2] = ysw ? (* src = "sram.v:12.10-12.13|sram.v:12.7-17.29" *) add[2] : 1'hx;
  assign _03_[0] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[0] : 1'hx;
  assign _03_[1] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[1] : 1'hx;
  assign _03_[2] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[2] : 1'hx;
  assign _03_[3] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[3] : 1'hx;
  assign _03_[4] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[4] : 1'hx;
  assign _03_[5] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[5] : 1'hx;
  assign _03_[6] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[6] : 1'hx;
  assign _03_[7] = ysr ? (* src = "sram.v:14.15-14.18|sram.v:14.12-17.29" *) _02_[7] : 1'hx;
endmodule
