/* Generated by Yosys 0.41+108 (git sha1 557968567, g++ 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "inverter.v:1.1-6.10" *)
module inverter(y, a);
  (* src = "inverter.v:3.11-3.12" *)
  input a;
  wire a;
  (* src = "inverter.v:2.12-2.13" *)
  output y;
  wire y;
  assign y = ~a;
endmodule
